CREATE TABLE course_fields_of_study
(
    course_id      NUMBER(38, 0) NOT NULL,
    field_of_study VARCHAR2(255)
);

CREATE TABLE courses
(
    oid           NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title         VARCHAR2(255),
    description   VARCHAR2(255),
    course_status VARCHAR2(255),
    course_type   VARCHAR2(255),
    pricing_type  VARCHAR2(255),
    created_at    TIMESTAMP                                      NOT NULL,
    updated_at    TIMESTAMP,
    CONSTRAINT pk_courses PRIMARY KEY (oid)
);

ALTER TABLE course_fields_of_study
    ADD CONSTRAINT fk_course_fields_of_study_on_course FOREIGN KEY (course_id) REFERENCES courses (oid);

CREATE TABLE modules
(
    oid         NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR2(255),
    description VARCHAR2(255),
    order_index INTEGER,
    course_oid  NUMBER(38, 0),
    CONSTRAINT pk_modules PRIMARY KEY (oid)
);

ALTER TABLE modules
    ADD CONSTRAINT FK_MODULES_ON_COURSE_OID FOREIGN KEY (course_oid) REFERENCES courses (oid);

CREATE TABLE assignments
(
    oid         NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR2(255),
    description VARCHAR2(255),
    status      INTEGER,
    grade       INTEGER,
    max_grade   INTEGER,
    min_grade   INTEGER,
    module_oid  NUMBER(38, 0),
    CONSTRAINT pk_assignments PRIMARY KEY (oid)
);

ALTER TABLE assignments
    ADD CONSTRAINT FK_ASSIGNMENTS_ON_MODULE_OID FOREIGN KEY (module_oid) REFERENCES modules (oid);

commit;